apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-workflow
  template:
    metadata:
      labels:
        app: devops-workflow
    spec:
      containers:
      - name: app
        image: yogeshrajendran/devops-workflow:latest
        ports:
        - containerPort: 80
